function foundations_names_definitions();

foundations_joints_names = strvcat ('foundations_side_prj',...
                                    'foundations_aft_prj',...
                                    'foundations_side_rvj',...
                                    'foundations_aft_rvj');
