function  blade_names_definition();



% REMARK : THIS IMPLEMENTATATION IS NOT EFFICIENT !!
% IT SHOULD BE BETTER IF I COPY THE SOLUTION USED
% FOR THE AERODYNAMIC !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
% !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


%-----------------------------------------------------
% Names associated to the BLADE-1- definition
%-----------------------------------------------------

point_mass_name{1} = strvcat ('rb_point_mass_1_1',...
    'rb_point_mass_2_1',...
    'rb_point_mass_3_1',...
    'rb_point_mass_4_1');

pt_mass_name = strvcat ('point_mass_1',...
    'point_mass_2',...
    'point_mass_3',...
    'point_mass_4');

pt_blade_root_name{1} = strvcat ('pt_blade_root_1_1',...
    'pt_blade_root_2_1',...
    'pt_blade_root_3_1',...
    'pt_blade_root_4_1');

pt_blade_tip_name{1} = strvcat ('pt_blade_tip_1_1',...
    'pt_blade_tip_2_1',...
    'pt_blade_tip_3_1',...
    'pt_blade_tip_4_1');

curve_blade_name{1} = strvcat ('curve_blade_1_1',...
    'curve_blade_2_1',...
    'curve_blade_3_1',...
    'curve_blade_4_1');

mesh_blade_name{1} = strvcat ('mesh_blade_1',...
    'mesh_blade_2',...
    'mesh_blade_3',...
    'mesh_blade_4');

prop_blade_name{1} = strvcat ('prop_blade_1',...
    'prop_blade_2',...
    'prop_blade_3',...
    'prop_blade_4');

blade_name{1} = strvcat ('blade_1_1',...
    'blade_2_1',...
    'blade_3_1',...
    'blade_4_1');

frame_name{1} = strvcat ('tower_frame',...
    'blade_root_frame_1',...
    'frame_hub');

%-----------------------------------------------------
% Names associated to the BLADE-2- definition
%-----------------------------------------------------

point_mass_name{2} = strvcat ('rb_point_mass_1_2',...
    'rb_point_mass_2_2',...
    'rb_point_mass_3_2',...
    'rb_point_mass_4_2');

% pt_mass_name{2} = strvcat ('point_mass_1_2',...
%     'point_mass_2_2',...
%     'point_mass_3_2',...
%     'point_mass_4_2');

pt_blade_root_name{2} = strvcat ('pt_blade_root_1_2',...
    'pt_blade_root_2_2',...
    'pt_blade_root_3_2',...
    'pt_blade_root_4_2');

pt_blade_tip_name{2} = strvcat ('pt_blade_tip_1_2',...
    'pt_blade_tip_2_2',...
    'pt_blade_tip_3_2',...
    'pt_blade_tip_4_2');

curve_blade_name{2} = strvcat ('curve_blade_1_2',...
    'curve_blade_2_2',...
    'curve_blade_3_2',...
    'curve_blade_4_2');

% mesh_blade_name{2} = strvcat ('mesh_blade_1',...
%     'mesh_blade_2',...
%     'mesh_blade_3',...
%     'mesh_blade_4');

prop_blade_name{2} = strvcat ('prop_blade_1',...
    'prop_blade_2',...
    'prop_blade_3',...
    'prop_blade_4');

blade_name{2} = strvcat ('blade_1_2',...
    'blade_2_2',...
    'blade_3_2',...
    'blade_4_2');

frame_name{2} = strvcat ('tower_frame',...
    'blade_root_frame_2',...
    'frame_hub');

%-----------------------------------------------------
% Names associated to the BLADE-3- definition
%-----------------------------------------------------

point_mass_name{3} = strvcat ('rb_point_mass_1_3',...
    'rb_point_mass_2_3',...
    'rb_point_mass_3_3',...
    'rb_point_mass_4_3');

% pt_mass_name{3} = strvcat ('point_mass_1_3',...
%     'point_mass_2_3',...
%     'point_mass_3_3',...
%     'point_mass_4_3');

pt_blade_root_name{3} = strvcat ('pt_blade_root_1_3',...
    'pt_blade_root_2_3',...
    'pt_blade_root_3_3',...
    'pt_blade_root_4_3');

pt_blade_tip_name{3} = strvcat ('pt_blade_tip_1_3',...
    'pt_blade_tip_2_3',...
    'pt_blade_tip_3_3',...
    'pt_blade_tip_4_3');

curve_blade_name{3} = strvcat ('curve_blade_1_3',...
    'curve_blade_2_3',...
    'curve_blade_3_3',...
    'curve_blade_4_3');

% mesh_blade_name{3} = strvcat ('mesh_blade_1',...
%     'mesh_blade_2',...
%     'mesh_blade_3',...
%     'mesh_blade_4');

prop_blade_name{3} = strvcat ('prop_blade_1',...
    'prop_blade_2',...
    'prop_blade_3',...
    'prop_blade_4');

blade_name{3} = strvcat ('blade_1_3',...
    'blade_2_3',...
    'blade_3_3',...
    'blade_4_3');

frame_name{3} = strvcat ('tower_frame',...
    'blade_root_frame_3',...
    'frame_hub');


%save names\blade_names blade_name prop_blade_name mesh_blade_name curve_blade_name pt_blade_tip_name pt_blade_root_name point_mass_name frame_name pt_mass_name

save blade_names blade_name prop_blade_name mesh_blade_name curve_blade_name pt_blade_tip_name pt_blade_root_name point_mass_name frame_name pt_mass_name