function NWP_grid_generation(z_hub,time_step,d,grid_size,grid_resolution,V_hub,V_NWP,time_nwp,dat_file_name)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function define and write the three wind conponents time history
% for all the points of the defined grid.
%
% Syntax:
%     -NWP_grid_generation(z_hub,time_step,d,grid_size,grid_resolution,V_hub,V_NWP,time_nwp)
%
% Input:
%     -z_hub     = it is a number which define the hub height above the ground
%                  level. -it is expressed in meters.
%     -time_step = this number define the time step at which the wind speed
%                  component are defined.
%     -d         = this number define the rotor diameter in meters.
%     -grid_size = it is a vector of two numbers which define the number of
%                  nodes above each side of the grid.
%     -grid_resolution = this number define the distance between two points
%                        of the grid.
%     -V_hub = defibe the longitudinal wind speed at the hub height.
%     -VNWP  = it is a vecitr which define the longitudinal wind speed at
%              each height of the grid: V_NWP=V_hub*[(z/z_hub).^alfa];
%              N.B. the wind shear potential law is taken into account.
%    -time_nwp = define the time lenght of the grid.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%





% ALEALE 24.04.2008
% fpc=fopen( strcat('Multibody\wind\','NWP.u') , 'w' );
fpc=fopen( strcat(dat_file_name(end,:),'\wind\','NWP.u') , 'w' );
%
time=datestr(now);
fprintf(fpc,'\nThis full-field IEC gust file was generated by AeroPolimiIECGusts (v1.00, 06-Ott-2004) on ');fprintf(fpc,time);fprintf(fpc,'\n\n');
fprintf(fpc,' | u-comp |  Y  x  Z  | Grid Resolution | Time-step | Hub Elev | Mean U |\n');
fprintf(fpc,'             %2.0f  %2.0f         %2.3f         %2.3f       %2.3f     %2.3f  \n\n' , grid_size,grid_resolution,time_step,z_hub,V_hub);
fprintf(fpc,' Z Coordinates (m):\n');
i=0;
while 1,
    fprintf(fpc,'  %2.5f ',-d/2+grid_resolution*i);
    i=i+1;
    if i == grid_size(1),
        break,
    end
end
fprintf(fpc,'\n\n');
fprintf(fpc,'');

fprintf(fpc,' Y Coordinates (m):\n');
i=0;
while 1,
    fprintf(fpc,'  %2.5f ',-d/2+grid_resolution*i);
    i=i+1;
    if i == grid_size(1),
        break,
    end
end
fprintf(fpc,'\n');


temp_time=0;
for t=0:time_step:time_nwp,
    
    fprintf(fpc,'\n  %2g   %2g \n',t,V_hub);
    fprintf(fpc,' ');    
    
    for iz=1:1:grid_size(2),
        
        for iy=1:1:grid_size(1),
            
            fprintf(fpc,'  %2.5f ',V_NWP(end-iz+1));
            
        end
        
        fprintf(fpc,' \n ');    
        
    end
    
end

    
fclose(fpc);

% ALEALE 24.04.2008
% fpc=fopen( strcat('Multibody\wind\','NWP.v') , 'w' );
fpc=fopen( strcat(dat_file_name(end,:),'\wind\','NWP.v') , 'w' );
%

time=datestr(now);
fprintf(fpc,'\nThis full-field IEC gust file was generated by AeroPolimiIECGusts (v1.00, 06-Ott-2004) on ');fprintf(fpc,time);fprintf(fpc,'\n\n');
fprintf(fpc,' | u-comp |  Y  x  Z  | Grid Resolution | Time-step | Hub Elev | Mean U |\n');
fprintf(fpc,'             %2.0f  %2.0f         %2.3f         %2.3f       %2.3f     %2.3f  \n\n' , grid_size,grid_resolution,time_step,z_hub,V_hub);
fprintf(fpc,' Z Coordinates (m):\n');
i=0;
while 1,
    fprintf(fpc,'  %2.5f ',-d/2+grid_resolution*i);
    i=i+1;
    if i == grid_size(1),
        break,
    end
end
fprintf(fpc,'\n\n');
fprintf(fpc,'');

fprintf(fpc,' Y Coordinates (m):\n');
i=0;
while 1,
    fprintf(fpc,'  %2.5f ',-d/2+grid_resolution*i);
    i=i+1;
    if i == grid_size(1),
        break,
    end
end
fprintf(fpc,'\n');


temp_time=0;
for t=0:time_step:time_nwp,
    
    fprintf(fpc,'\n  %2g   %2g \n',t,V_hub*0);
    fprintf(fpc,' ');    
    
    for iz=1:1:grid_size(2),
        
        for iy=1:1:grid_size(1),
            
            fprintf(fpc,'  %2.5f ',V_NWP(end-iz+1)*0);
            
        end
        
        fprintf(fpc,' \n ');    
        
    end
    
end

    
fclose(fpc);



% ALEALE 24.04.2008
% fpc=fopen( strcat('Multibody\wind\','NWP.w') , 'w' );
fpc=fopen( strcat(dat_file_name(end,:),'\wind\','NWP.w') , 'w' );
%
time=datestr(now);
fprintf(fpc,'\nThis full-field IEC gust file was generated by AeroPolimiIECGusts (v1.00, 06-Ott-2004) on ');fprintf(fpc,time);fprintf(fpc,'\n\n');
fprintf(fpc,' | u-comp |  Y  x  Z  | Grid Resolution | Time-step | Hub Elev | Mean U |\n');
fprintf(fpc,'             %2.0f  %2.0f         %2.3f         %2.3f       %2.3f     %2.3f  \n\n' , grid_size,grid_resolution,time_step,z_hub,V_hub);
fprintf(fpc,' Z Coordinates (m):\n');
i=0;
while 1,
    fprintf(fpc,'  %2.5f ',-d/2+grid_resolution*i);
    i=i+1;
    if i == grid_size(1),
        break,
    end
end
fprintf(fpc,'\n\n');
fprintf(fpc,'');

fprintf(fpc,' Y Coordinates (m):\n');
i=0;
while 1,
    fprintf(fpc,'  %2.5f ',-d/2+grid_resolution*i);
    i=i+1;
    if i == grid_size(1),
        break,
    end
end
fprintf(fpc,'\n');


temp_time=0;
for t=0:time_step:time_nwp,
    
    fprintf(fpc,'\n  %2g   %2g \n',t,V_hub*0);
    fprintf(fpc,' ');    
    
    for iz=1:1:grid_size(2),
        
        for iy=1:1:grid_size(1),
            
            fprintf(fpc,'  %2.5f ',V_NWP(end-iz+1)*0);
            
        end
        
        fprintf(fpc,' \n ');    
        
    end
    
end

    
fclose(fpc);