function wind_grid_print_EWS(time_gust,gust_name,grid_size,grid_resolution,time_step,z_hub,V_hub,d,V_gust_hub,V_gust,time_trans_1,time_trans_2, dat_file_name)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function generates the user defined wind grid for the deterministic  %
% IEC gusts.                                                                %
%                                                                           %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% fpc=fopen( strcat('Multibody\wind\',gust_name) , 'w' );
fpc=fopen( strcat(dat_file_name(end,:),'\Wind\',gust_name) , 'w' );

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FILE HEADER (Same of SNwind layout)   %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
time=datestr(now);
fprintf(fpc,'\nThis full-field IEC-gust file was generated by AeroPolimiIECGusts (v1.00, 06-Ott-2004) on ');fprintf(fpc,time);fprintf(fpc,'\n\n');
fprintf(fpc,' | u-comp |  Y  x  Z  | Grid Resolution | Time-step | Hub Elev | Mean U |\n');
fprintf(fpc,'             %2.0f  %2.0f         %2.3f         %2.3f       %2.3f     %2.3f  \n\n' , grid_size,grid_resolution,time_step,z_hub,V_hub);
fprintf(fpc,' Z Coordinates (m):\n');
i=0;
while 1,
    fprintf(fpc,'  %2.5f ',-d/2+grid_resolution*i);
    i=i+1;
    if i == grid_size(1),
        break,
    end
end
fprintf(fpc,'\n\n');
fprintf(fpc,'');

fprintf(fpc,' Y Coordinates (m):\n');
i=0;
while 1,
    fprintf(fpc,'  %2.5f ',-d/2+grid_resolution*i);
    i=i+1;
    if i == grid_size(1),
        break,
    end
end
fprintf(fpc,'\n');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% WInd-Grid generation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Initial constant wind
for t=1:1:(time_trans_1/time_step),
    
    fprintf(fpc,'\n  %2g   %2g \n',t*time_step-time_step,V_gust_hub(1));
    fprintf(fpc,' ');    
    
    for iz=1:1:grid_size(2),
        
        for iy=1:1:grid_size(1),
            
            fprintf(fpc,'  %2.5f ',V_gust(1,end-iz+1,iy));
            
        end
        
        fprintf(fpc,' \n ');    
        
    end
    
end

% transitory wind
for t=1:1:(time_gust/time_step),
    
    fprintf(fpc,'\n  %2g   %2g \n',time_trans_1+t*time_step-time_step,V_gust_hub(t));
    fprintf(fpc,' ');    
    
    for iz=1:1:grid_size(2),
        
        for iy=1:1:grid_size(1),
            
            fprintf(fpc,'  %2.5f ',V_gust(t,end-iz+1,iy));
            
        end
        
        fprintf(fpc,' \n ');    
        
    end
    
end

% stationary final wind
for t=1:1:(time_trans_2/time_step),
    
    fprintf(fpc,'\n  %2g   %2g \n',time_trans_1+time_gust+t*time_step-time_step,V_gust_hub(end));
    fprintf(fpc,' ');    
    
    for iz=1:1:grid_size(2),
        
        for iy=1:1:grid_size(1),
            
            fprintf(fpc,'  %2.5f ',V_gust(end,end-iz+1,iy));
            
        end
        
        fprintf(fpc,' \n ');    
        
    end
    
end

    
fclose(fpc);