function aerodynamic_names();

%----------------------------------------
% This function define and storage the
% names needed to define the multibody
% model's aerodynamic.
%----------------------------------------

%% ALEALE 16.04.2013 new definitions
index=[1:1000];

%
lifting_line_name = [];
for i=1:6
    lifting_line_name = strvcat(lifting_line_name,sprintf('lifting_line_%i',i));
end

%
pt_lifting_name = [];
for i=1:12
    pt_lifting_name = strvcat(pt_lifting_name,sprintf('pt_lifting_%i',i));
end

%
airtable_names = [];
for i=1:300
    airtable_names = strvcat(airtable_names,sprintf('airtable_%i',i));
end

%
lifting_triad_name = [];
for i=1:12
    lifting_triad_name = strvcat(lifting_triad_name,sprintf('lifting_triad_%i',i));
end

%
lifting_curve_name = [];
for i=1:12
    lifting_curve_name = strvcat(lifting_curve_name,sprintf('lifting_curve_%i',i));
end

%
lifting_line_prop_name = [];
for i=1:12
    lifting_line_prop_name = strvcat(lifting_line_prop_name,sprintf('lifting_prop_%i',i));
end



inflow_model_names = strvcat ('rotor_inflow' , ...  %1
    'inflow_triad' , ...  %2
    '' , ...   %3
    '' , ...   %4
    '' );      %5


save aero_names airtable_names pt_lifting_name lifting_line_name lifting_triad_name lifting_curve_name lifting_line_prop_name inflow_model_names

return



lifting_line_name = strvcat('lifting_line_1' , ...
                            'lifting_line_2' , ...
                            'lifting_line_3' , ...
                            'lifting_line_4' , ...
                            'lifting_line_5' , ...
                            'lifting_line_6');

pt_lifting_name = strvcat ( 'pt_lifting_1' , ...
                            'pt_lifting_2' , ...
                            'pt_lifting_3' , ...
                            'pt_lifting_4' , ...
                            'pt_lifting_5' , ...
                            'pt_lifting_6' , ...
                            'pt_lifting_7' , ...
                            'pt_lifting_8' , ...
                            'pt_lifting_9' , ...
                            'pt_lifting_10' , ...
                            'pt_lifting_11' );

airtable_names = strvcat ('airtable_1' , ...
                          'airtable_2' , ...
                          'airtable_3' , ...
                          'airtable_4' , ...
                          'airtable_5' , ...
                          'airtable_6' , ...
                          'airtable_7' , ...
                          'airtable_8' , ...
                          'airtable_9' , ...
                          'airtable_10' , ...
                          'airtable_11' , ...
                          'airtable_12' , ...
                          'airtable_13' , ...
                          'airtable_14' , ...
                          'airtable_15' , ...
                          'airtable_16' , ...
                          'airtable_17' , ...
                          'airtable_18' , ...
                          'airtable_19' , ...
                          'airtable_20' , ...
                          'airtable_21' , ...
                          'airtable_22' , ...
                          'airtable_23' , ...
                          'airtable_24' , ...
                          'airtable_25' , ...
                          'airtable_26' , ...
                          'airtable_27' , ...
                          'airtable_28' , ...
                          'airtable_29' , ...
                          'airtable_30' , ...
                          'airtable_31' , ...
                          'airtable_32' , ...
                          'airtable_33' , ...
                          'airtable_34' , ...
                          'airtable_35' , ...
                          'airtable_36' , ...
                          'airtable_37' , ...
                          'airtable_38' , ...
                          'airtable_39' , ...
                          'airtable_40' , ...
                          'airtable_41' , ...
                          'airtable_42' , ...
                          'airtable_43' , ...
                          'airtable_44' , ...
                          'airtable_45' , ...
                          'airtable_46' , ...
                          'airtable_47' , ...
                          'airtable_48' , ...
                          'airtable_49' , ...
                          'airtable_50' , ...
                          'airtable_51' , ...
                          'airtable_52' , ...
                          'airtable_53' , ...
                          'airtable_54' , ...
                          'airtable_55' , ...
                          'airtable_56' , ...
                          'airtable_57' , ...
                          'airtable_58' , ...
                          'airtable_59' , ...
                          'airtable_60' , ...
                          'airtable_61' , ...
                          'airtable_62' , ...
                          'airtable_63' , ...
                          'airtable_64' , ...
                          'airtable_65' , ...
                          'airtable_66' , ...
                          'airtable_67' , ...
                          'airtable_68' , ...
                          'airtable_69' , ...
                          'airtable_70' , ...
                          'airtable_71' , ...
                          'airtable_72' , ...
                          'airtable_73' , ...
                          'airtable_74' , ...
                          'airtable_75' , ...
                          'airtable_76' , ...
                          'airtable_77' , ...
                          'airtable_78' , ...
                          'airtable_79' , ...
                          'airtable_80' , ...
                          'airtable_81' , ...
                          'airtable_82' , ...
                          'airtable_83' , ...
                          'airtable_84' , ...
                          'airtable_85' , ...
                          'airtable_86' , ...
                          'airtable_87' , ...
                          'airtable_88' , ...
                          'airtable_89' , ...
                          'airtable_90' , ...
                          'airtable_91' , ...
                          'airtable_92' , ...
                          'airtable_93' , ...
                          'airtable_94' , ...
                          'airtable_95' , ...
                          'airtable_96' , ...
                          'airtable_97' , ...
                          'airtable_98' , ...
                          'airtable_99' , ...
                          'airtable_100' , ...
                          'airtable_101' , ...
                          'airtable_102' );

                                             
lifting_triad_name = strvcat ('lifting_triad_1' , ...
                              'lifting_triad_2' , ...
                              'lifting_triad_3' , ...
                              'lifting_triad_4' , ...
                              'lifting_triad_5' , ...
                              'lifting_triad_6' , ...
                              'lifting_triad_7' , ...
                              'lifting_triad_8' , ...
                              'lifting_triad_9' , ...
                              'lifting_triad_10');
                                             
lifting_curve_name = strvcat ('lifting_curve_1' , ...
                              'lifting_curve_2' , ...
                              'lifting_curve_3' , ...
                              'lifting_curve_4' , ...
                              'lifting_curve_5' , ...
                              'lifting_curve_6' , ...
                              'lifting_curve_7' , ...
                              'lifting_curve_8' , ...           
                              'lifting_curve_9' , ...           
                              'lifting_curve_10');              
                                                                
                                                                
lifting_line_prop_name = strvcat ('lifting_prop_1' , ...        
                                  'lifting_prop_2' , ...        
                                  'lifting_prop_3' , ...        
                                  'lifting_prop_4' , ...        
                                  'lifting_prop_5' , ...        
                                  'lifting_prop_6' , ...        
                                  'lifting_prop_7' , ...        
                                  'lifting_prop_8' , ...        
                                  'lifting_prop_9' , ...        
                                  'lifting_prop_10' );          
                                                                
inflow_model_names = strvcat ('rotor_inflow' , ...  %1          
                              'inflow_triad' , ...  %2          
                              '' , ...   %3                     
                              '' , ...   %4                     
                              '' );      %5                     


%save names\aero_names airtable_names pt_lifting_name lifting_line_name lifting_triad_name lifting_curve_name lifting_line_prop_name inflow_model_names

save aero_names airtable_names pt_lifting_name lifting_line_name lifting_triad_name lifting_curve_name lifting_line_prop_name inflow_model_names
